# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brann.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_brann(object):
    def setupUi(self, brann):
        brann.setObjectName("brann")
        brann.setWindowModality(QtCore.Qt.NonModal)
        brann.resize(480, 320)
        brann.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label = QtWidgets.QLabel(brann)
        self.label.setGeometry(QtCore.QRect(56, 52, 371, 201))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(brann)
        QtCore.QMetaObject.connectSlotsByName(brann)

    def retranslateUi(self, brann):
        _translate = QtCore.QCoreApplication.translate
        brann.setWindowTitle(_translate("brann", "BRANN"))
        self.label.setText(_translate("brann", "Brannalarm"))


def brann_alarm():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    brann = QtWidgets.QWidget()
    ui = Ui_brann()
    ui.setupUi(brann)
    brann.show()
    sys.exit(app.exec_())
