# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meny.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_meny(object):

    def setupUi(self, meny):
        meny.setObjectName("meny")
        meny.resize(480, 320)
        meny.setStyleSheet("background-color: rgb(103, 103, 103);")
        self.centralwidget = QtWidgets.QWidget(meny)
        self.centralwidget.setObjectName("centralwidget")
        self.nokfelles_button = QtWidgets.QPushButton(self.centralwidget)
        self.nokfelles_button.setGeometry(QtCore.QRect(260, 200, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.nokfelles_button.setFont(font)
        self.nokfelles_button.setStyleSheet("background-color: rgb(255, 117, 124);")
        self.nokfelles_button.setObjectName("nokfelles_button")
        self.nokbrukere_button = QtWidgets.QPushButton(self.centralwidget)
        self.nokbrukere_button.setGeometry(QtCore.QRect(260, 120, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.nokbrukere_button.setFont(font)
        self.nokbrukere_button.setStyleSheet("background-color: rgb(255, 117, 124);")
        self.nokbrukere_button.setObjectName("nokbrukere_button")
        self.solcelle_button = QtWidgets.QPushButton(self.centralwidget)
        self.solcelle_button.setEnabled(True)
        self.solcelle_button.setGeometry(QtCore.QRect(140, 40, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.solcelle_button.setFont(font)
        self.solcelle_button.setStyleSheet("background-color: rgb(255, 117, 124);")
        self.solcelle_button.setObjectName("solcelle_button")
        self.kwhfelles_button = QtWidgets.QPushButton(self.centralwidget)
        self.kwhfelles_button.setGeometry(QtCore.QRect(30, 200, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.kwhfelles_button.setFont(font)
        self.kwhfelles_button.setStyleSheet("background-color: rgb(255, 117, 124);")
        self.kwhfelles_button.setObjectName("kwhfelles_button")
        self.kwhbrukere_button = QtWidgets.QPushButton(self.centralwidget)
        self.kwhbrukere_button.setGeometry(QtCore.QRect(30, 120, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.kwhbrukere_button.setFont(font)
        self.kwhbrukere_button.setStyleSheet("background-color: rgb(255, 117, 124);")
        self.kwhbrukere_button.setObjectName("kwhbrukere_button")
        meny.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(meny)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        meny.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(meny)
        self.statusbar.setObjectName("statusbar")
        meny.setStatusBar(self.statusbar)

        self.retranslateUi(meny)
        QtCore.QMetaObject.connectSlotsByName(meny)

    def retranslateUi(self, meny):
        _translate = QtCore.QCoreApplication.translate
        meny.setWindowTitle(_translate("meny", "meny"))
        self.nokfelles_button.setText(_translate("meny", "NOK felles"))
        self.nokbrukere_button.setText(_translate("meny", "NOK brukere"))
        self.solcelle_button.setText(_translate("meny", "Solceller"))
        self.kwhfelles_button.setText(_translate("meny", "kWh felles"))
        self.kwhbrukere_button.setText(_translate("meny", "kWh brukere"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    meny = QtWidgets.QMainWindow()
    ui = Ui_meny()
    ui.setupUi(meny)
    meny.show()
    sys.exit(app.exec_())
