# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solceller.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_solceller(object):
    def setupUi(self, solceller):
        solceller.setObjectName("solceller")
        solceller.resize(480, 320)
        solceller.setAutoFillBackground(False)
        solceller.setStyleSheet("background-color: rgb(131, 131, 131);")
        self.centralwidget = QtWidgets.QWidget(solceller)
        self.centralwidget.setObjectName("centralwidget")
        self.graph = QtWidgets.QPushButton(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(380, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.graph.setFont(font)
        self.graph.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.graph.setObjectName("graph")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(20, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.back.setObjectName("back")
        self.stop_dato = QtWidgets.QLabel(self.centralwidget)
        self.stop_dato.setGeometry(QtCore.QRect(50, 100, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.stop_dato.setFont(font)
        self.stop_dato.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.stop_dato.setObjectName("stop_dato")
        self.dateedit1 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateedit1.setGeometry(QtCore.QRect(190, 50, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateedit1.setFont(font)
        self.dateedit1.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.dateedit1.setObjectName("dateedit1")
        self.start_dato = QtWidgets.QLabel(self.centralwidget)
        self.start_dato.setGeometry(QtCore.QRect(50, 50, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.start_dato.setFont(font)
        self.start_dato.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.start_dato.setObjectName("start_dato")
        self.dateedit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateedit_2.setGeometry(QtCore.QRect(190, 100, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateedit_2.setFont(font)
        self.dateedit_2.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.dateedit_2.setObjectName("dateedit_2")
        solceller.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(solceller)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        solceller.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(solceller)
        self.statusbar.setObjectName("statusbar")
        solceller.setStatusBar(self.statusbar)

        self.retranslateUi(solceller)
        QtCore.QMetaObject.connectSlotsByName(solceller)

    def retranslateUi(self, solceller):
        _translate = QtCore.QCoreApplication.translate
        solceller.setWindowTitle(_translate("solceller", "solceller"))
        self.graph.setText(_translate("solceller", "graph"))
        self.back.setText(_translate("solceller", "back"))
        self.stop_dato.setText(_translate("solceller", "Stop dato"))
        self.start_dato.setText(_translate("solceller", "Start dato"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    solceller = QtWidgets.QMainWindow()
    ui = Ui_solceller()
    ui.setupUi(solceller)
    solceller.show()
    sys.exit(app.exec_())
